import type { CompanyNarrative } from "../types";

export const companyNarratives: Record<string, CompanyNarrative> = {
  "aurora-metals": {
    frameworkVersion: 2,
    identity: "A celebrated veteran team attempting one final impossible build.",
    personalityArchetype: "engineer",
    belief: "Difficult assets become real when experienced builders accept responsibility for the details.",
    coreDesire: "Prove that hard-earned craft still matters more than fashionable storytelling.",
    greatestStrength: "The team has finished difficult projects before and understands what failure looks like up close.",
    fatalFlaw: "Past success makes leadership slow to recognize when the present is fundamentally different.",
    companyCulture: "Loyal, technically proud, apprenticeship-driven, and reluctant to challenge senior builders in public.",
    investorExcitement: "A proven team may be able to turn a neglected district into a durable operating asset.",
    investorHesitation: "The plan is expensive, remote, and unusually dependent on leaders near the end of their careers.",
    biggestCatalyst: "Construction reaches the point where execution replaces reputation as evidence.",
    biggestUnknown: "Whether Aurora’s institution is deeper than its famous veterans.",
    hiddenTruth: "The famous founder is no longer making the most important operating decisions.",
    secretOpportunity: "A deeper zone could extend the district into a multi-generation asset.",
    secretWeakness: "Several senior operators may retire before construction reaches its hardest stage.",
    moralDilemma: "Protect the old team’s legacy or replace loyal veterans with people suited to the new reality.",
    longTermAmbition: "Build a district that outlives every person currently leading it.",
    fear: "Be remembered as builders who stayed one project too long.",
    founderStory: "Mara Vale earned her reputation rebuilding a mine everyone else had abandoned; Aurora is the promise she made to prove it was skill, not luck.",
    currentChapter: "The veteran team has secured a final district and must prove its old methods still work under new constraints.",
    futurePossibilities: ["A multigeneration district emerges.", "A disciplined takeover preserves the asset.", "Succession failure turns a final build into a final mistake."],
    rivals: [{ companyId: "terranova-copper", relationship: "Competing claim to strategic infrastructure", tension: "Only one project may receive priority access through the mountain corridor." }],
    allies: [{ companyId: "bluepeak-minerals", relationship: "Shared engineering culture", tension: "BluePeak can solve Aurora’s access problem, but expects influence in return." }],
    relationshipHooks: ["Reward patience after a construction delay.", "Remember players who replace the founder’s loyal team.", "Offer TerraNova’s takeover interest after Aurora appears weak."],
    macroTriggers: [
      { id: "aurora-metal-cycle", when: "Commodity demand rises while construction remains unfinished.", storyBeat: "The market rewards Aurora before the mine proves it can operate.", tags: ["commodity-boom", "hype", "construction"] },
      { id: "aurora-cost-regime", when: "Cost inflation arrives with a weak balance sheet.", storyBeat: "Experience cannot negotiate with every rising input at once.", tags: ["inflation", "financing", "crisis"] },
    ],
    crisisArcs: [
      { id: "aurora-last-build", title: "The Last Build", premise: "A serious delay forces the veterans to choose between pride and outside help.", triggerTags: ["delay", "execution", "founder"], beats: ["The schedule slips.", "A younger operator challenges the plan.", "The founder must surrender control or double down."], unresolvedQuestion: "Can a great builder remain great by admitting the old method no longer works?" },
      { id: "aurora-succession", title: "Empty Chair at the Summit", premise: "The founder’s health makes succession unavoidable.", triggerTags: ["leadership", "retirement"], beats: ["Rumors spread.", "Two successors emerge.", "Loyalty divides the operating team."], unresolvedQuestion: "Is Aurora an institution or a biography?" },
    ],
    comebackArcs: [{ id: "aurora-first-pour", title: "The Furnace Answers", premise: "After repeated delays, the first production proves the team still knows how to finish.", triggerTags: ["hold", "execution", "recovery"], beats: ["The final bottleneck clears.", "Costs stabilize.", "The first shipment leaves the valley."], unresolvedQuestion: "Was the victory repeatable, or the last act of an exceptional generation?" }],
    legendaryEndings: [{ id: "aurora-cathedral", title: "The Cathedral in the Mountain", legend: "Aurora becomes the district every future builder studies.", condition: "Back Aurora through multiple crises and preserve both execution quality and institutional succession." }],
    hiddenEndings: [{ id: "aurora-teacher", title: "The Builders Who Walked Away", legend: "Aurora sells the deposit and turns its veteran team into a school for the next generation.", condition: "Discover the succession truth, reject empire, and accept a disciplined takeover." }],
    stakeholders: [{ name: "Vale Construction Guild", role: "supplier", leverage: "Controls the veteran contractor bench.", tension: "Loyalty may outlive performance." }, { name: "Mountain Works Authority", role: "regulator", leverage: "Controls corridor permits.", tension: "Wants shared regional infrastructure." }],
    narrativeVariables: [{ id: "aurora-costs", variable: "construction costs", condition: "Costs rise after rapid expansion.", consequence: "Experience helps sequencing but cannot prevent financing pressure.", affectedRelationships: ["bluepeak-minerals", "terranova-copper"] }, { id: "aurora-succession-variable", variable: "founder control", condition: "The founder stays through repeated delays.", consequence: "Loyalty rises while institutional depth erodes.", affectedRelationships: ["Vale Construction Guild"] }],
    arcCategories: {},
    eventTriggers: [
      { id: "aurora-delay-memory", when: "A permitting or construction delay occurs.", storyBeat: "Aurora remembers whether the player held, researched, or abandoned it.", tags: ["memory", "delay"] },
      { id: "aurora-takeover-choice", when: "A takeover rumor follows visible weakness.", storyBeat: "TerraNova’s advisers quietly enter the valley.", tags: ["takeover", "rival"] },
    ],
  },
  "ironwood-resources": {
    frameworkVersion: 2,
    identity: "The unfashionable provider that keeps working while louder stories collapse.",
    personalityArchetype: "silent-compounder",
    belief: "Reliability creates more freedom than excitement.",
    coreDesire: "Be valued for durability without becoming something it is not.",
    greatestStrength: "Reliable cash generation and disciplined operations.",
    fatalFlaw: "Caution can harden into complacency and starve the future.",
    companyCulture: "Frugal, operationally exact, skeptical of consultants, and quietly proud of never needing rescue.",
    investorExcitement: "Durable cash generation can compound while attention remains elsewhere.",
    investorHesitation: "Deferred reinvestment and customer concentration may make stability temporary.",
    biggestCatalyst: "The logistics network wins customers beyond the original mine.",
    biggestUnknown: "Whether its oldest customer leaves before a second engine is ready.",
    hiddenTruth: "Its oldest customer is quietly preparing to leave.",
    secretOpportunity: "Its logistics network could become more valuable than the mine itself.",
    secretWeakness: "Management has postponed replacement investment for too long.",
    moralDilemma: "Return cash to loyal owners or reinvest before the old operation begins to decay.",
    longTermAmbition: "Become the indispensable quiet infrastructure behind an entire region.",
    fear: "Wake up profitable, respected, and suddenly obsolete.",
    founderStory: "Two siblings bought unwanted equipment after a bankruptcy and built Ironwood by refusing every fashionable expansion.",
    currentChapter: "The operation remains profitable, but the decisions it postponed are becoming harder to ignore.",
    futurePossibilities: ["A quiet logistics compounder emerges.", "Customer loss forces reinvention.", "Complacency slowly consumes the advantage."],
    rivals: [{ companyId: "emberrock-mining", relationship: "Low-cost discipline versus endless turnaround", tension: "EmberRock wants Ironwood’s customers and calls its caution cowardice." }],
    allies: [{ companyId: "helio-rare-earths", relationship: "Quiet contractual partners", tension: "Helio’s hidden license can protect Ironwood’s margins if both sides trust the other." }],
    relationshipHooks: ["Reward players who notice maintenance before a breakdown.", "Reference missed growth when optionality is repeatedly ignored.", "Let EmberRock poach customers after Ironwood becomes complacent."],
    macroTriggers: [{ id: "ironwood-recession", when: "A broad downturn punishes fragile companies.", storyBeat: "Ironwood’s boring contracts become a form of power.", tags: ["recession", "cash-flow", "durability"] }],
    crisisArcs: [{ id: "ironwood-anchor-leaves", title: "The Silent Customer", premise: "The customer that built Ironwood’s stability declines to renew.", triggerTags: ["customer", "cash-flow", "hidden-truth"], beats: ["Volumes soften.", "Management denies concentration risk.", "A rival offers to buy the logistics network."], unresolvedQuestion: "Was Ironwood durable, or merely dependent?" }],
    comebackArcs: [{ id: "ironwood-second-engine", title: "The Boring Reinvention", premise: "Ironwood turns its neglected logistics network into a second business.", triggerTags: ["infrastructure", "reinvestment"], beats: ["A pilot contract appears.", "Old equipment finds a new purpose.", "The market notices recurring revenue."], unresolvedQuestion: "Can reinvention remain disciplined once attention arrives?" }],
    legendaryEndings: [{ id: "ironwood-compounder", title: "The Hundred Quiet Quarters", legend: "Ironwood compounds for a generation without needing to become famous.", condition: "Protect maintenance, diversify customers, and resist a hype-driven expansion." }],
    hiddenEndings: [{ id: "ironwood-public-road", title: "The Company That Became a Road", legend: "Ironwood spins out its network as shared infrastructure and outlives its original mine.", condition: "Discover the logistics opportunity and choose regional usefulness over extraction growth." }],
    stakeholders: [{ name: "Northern Foundry Cooperative", role: "customer", leverage: "Represents the anchor contract.", tension: "Quietly tests alternative suppliers." }, { name: "Ironwood Family Council", role: "founder", leverage: "Controls capital allocation.", tension: "Disagrees over dividends versus reinvestment." }],
    narrativeVariables: [{ id: "ironwood-demand", variable: "industrial demand", condition: "Demand weakens while the balance sheet remains strong.", consequence: "Ironwood can acquire distressed logistics assets.", affectedRelationships: ["emberrock-mining"] }, { id: "ironwood-maintenance-variable", variable: "deferred maintenance", condition: "Reinvestment is postponed twice.", consequence: "Cash flow looks stronger until reliability suddenly breaks.", affectedRelationships: ["Northern Foundry Cooperative"] }],
    arcCategories: {},
    eventTriggers: [{ id: "ironwood-maintenance", when: "Infrastructure weakens or costs rise.", storyBeat: "Deferred maintenance stops being invisible.", tags: ["maintenance", "costs"] }],
  },
  "silver-mammoth": {
    frameworkVersion: 2,
    identity: "A breathtaking possibility carried by a company too fragile to deserve certainty.",
    personalityArchetype: "explorer",
    belief: "One honest discovery can repay years of being misunderstood.",
    coreDesire: "Find enough proof before the treasury runs out.",
    greatestStrength: "An unusually large potential discovery with multiple ways to surprise the world.",
    fatalFlaw: "Every promising signal encourages spending as though success were already proven.",
    companyCulture: "Curious, improvisational, field-led, and dangerously tolerant of financial fragility.",
    investorExcitement: "A genuinely exceptional deposit could transform the entire frontier.",
    investorHesitation: "The company may run out of money or control before geology provides an answer.",
    biggestCatalyst: "A decisive result proves the scale and continuity of the system.",
    biggestUnknown: "Whether the best mineralization lies inside ground Mammoth controls.",
    hiddenTruth: "The best result may sit across a boundary the company does not control.",
    secretOpportunity: "A larger geological system could make Mammoth strategically unavoidable.",
    secretWeakness: "The next financing gives a promoter effective control over the company.",
    moralDilemma: "Dilute early believers to keep exploring or stop before the answer is known.",
    longTermAmbition: "Make the discovery that redraws the frontier.",
    fear: "Become a famous chart attached to a deposit that never becomes a mine.",
    founderStory: "A field geologist mortgaged everything after finding one impossible sample and has spent a decade trying to prove it was not an accident.",
    currentChapter: "Promising evidence has attracted attention just as the treasury approaches another limit.",
    futurePossibilities: ["A world-scale district is discovered.", "A larger partner takes control of the answer.", "The final test reveals only an unforgettable dream."],
    rivals: [{ companyId: "aurora-metals", relationship: "Dreamer versus builder", tension: "Aurora dismisses Mammoth as geology without a path to construction." }],
    allies: [{ companyId: "terranova-copper", relationship: "Potential strategic rescuer", tension: "TerraNova can fund the answer but may take the discovery from early believers." }],
    relationshipHooks: ["Remember who believed before proof.", "Punish blind loyalty after repeated dilution.", "Let Aurora’s experts validate or reject the discovery."],
    macroTriggers: [{ id: "mammoth-silver-fever", when: "Commodity prices and market hype rise together.", storyBeat: "Mammoth can finance easily, but truth becomes harder to hear beneath excitement.", tags: ["boom", "hype", "financing"] }],
    crisisArcs: [{ id: "mammoth-last-hole", title: "The Last Hole", premise: "The treasury can fund one final test.", triggerTags: ["dry-hole", "financing", "geology"], beats: ["The board chooses a target.", "A rival interpretation emerges.", "The drill enters the unknown."], unresolvedQuestion: "Is conviction courage when the evidence is incomplete—or denial when the treasury is empty?" }],
    comebackArcs: [{ id: "mammoth-deeper", title: "Deeper Than Doubt", premise: "A follow-up result reveals the failed test stopped just short of the real system.", triggerTags: ["discovery", "research", "near-miss"], beats: ["Old data is re-read.", "A deeper target forms.", "The market returns reluctantly."], unresolvedQuestion: "Will the second chance create discipline or restart the same fever?" }],
    legendaryEndings: [{ id: "mammoth-world-class", title: "The Mammoth Beneath the Dust", legend: "The frontier discovery becomes a world-scale district.", condition: "Fund disciplined research, survive dilution, and reveal exceptional geology." }],
    hiddenEndings: [{ id: "mammoth-walk-away", title: "The Hole Not Drilled", legend: "The company returns its remaining cash rather than sell one more dream.", condition: "Reveal weak control and choose intellectual honesty over another financing." }],
    stakeholders: [{ name: "Frontier Drilling Syndicate", role: "supplier", leverage: "Controls the only rig available this season.", tension: "Gets paid whether the thesis survives." }, { name: "Morrow Family Trust", role: "founder", leverage: "Holds the original geological archive.", tension: "Needs vindication more than liquidity." }],
    narrativeVariables: [{ id: "mammoth-metal-price", variable: "silver price", condition: "Price rises before geological proof.", consequence: "Financing improves while discipline weakens.", affectedRelationships: ["terranova-copper"] }, { id: "mammoth-player-research", variable: "player-funded research", condition: "The player researches before investing repeatedly.", consequence: "Deeper targets can appear without promoter-driven hype.", affectedRelationships: ["aurora-metals"] }],
    arcCategories: {},
    eventTriggers: [{ id: "mammoth-financing-memory", when: "Financing follows a major discovery or failure.", storyBeat: "The terms depend on whether the player previously rewarded promotion or demanded evidence.", tags: ["memory", "dilution"] }],
  },
  "borealis-energy": {
    frameworkVersion: 2,
    identity: "A stranded strategic asset waiting for history to need it again.",
    personalityArchetype: "fallen-giant",
    belief: "Strategic scarcity eventually defeats short-term indifference.",
    coreDesire: "Survive long enough for the energy cycle to return.",
    greatestStrength: "Scarce strategic exposure that cannot be recreated quickly.",
    fatalFlaw: "Being early feels indistinguishable from being wrong for long stretches of time.",
    companyCulture: "Patient, austere, regionally loyal, and accustomed to being dismissed by distant capital.",
    investorExcitement: "A change in energy security can make a forgotten asset indispensable almost overnight.",
    investorHesitation: "The wait consumes capital, infrastructure ages, and political consent cannot be assumed.",
    biggestCatalyst: "Regional transmission connects the asset to a market that needs it.",
    biggestUnknown: "Whether community consent survives a rapid strategic push.",
    hiddenTruth: "A local community holds an old agreement that can stop expansion.",
    secretOpportunity: "A neighboring grid project could transform the asset’s economics overnight.",
    secretWeakness: "Cold-weather infrastructure requires more replacement capital than public estimates admit.",
    moralDilemma: "Push development during a strategic shortage or renegotiate patiently with the people who live there.",
    longTermAmbition: "Become the stable energy reserve a vulnerable region cannot do without.",
    fear: "Run out of patience one season before the world finally changes.",
    founderStory: "Borealis began when a former grid planner bought rights nobody wanted after a policy reversal and refused to sell them back cheaply.",
    currentChapter: "The strategic argument is strengthening, but the physical and political route remains incomplete.",
    futurePossibilities: ["The Northern Reserve becomes essential.", "A community partnership creates durable legitimacy.", "Another cycle passes before access arrives."],
    rivals: [{ companyId: "terranova-copper", relationship: "Competing strategic priority", tension: "Governments may fund electrification metals or energy security first, but not both." }],
    allies: [{ companyId: "bluepeak-minerals", relationship: "Shared transmission destiny", tension: "A successful corridor unlocks both companies; failure strands them together." }],
    relationshipHooks: ["Reward players who distinguish cycle patience from passive hope.", "Make community trust respond to credibility decisions.", "Tie BluePeak infrastructure outcomes to Borealis economics."],
    macroTriggers: [{ id: "borealis-security-shock", when: "Energy security becomes politically urgent.", storyBeat: "Borealis changes from forgotten inventory into strategic leverage.", tags: ["energy", "security", "policy"] }],
    crisisArcs: [{ id: "borealis-frozen-road", title: "The Winter That Did Not End", premise: "Infrastructure failure removes an entire operating season.", triggerTags: ["arctic", "infrastructure", "delay"], beats: ["The road closes.", "Cash burn accelerates.", "A government rescue arrives with conditions."], unresolvedQuestion: "Does strategic importance protect owners—or only the asset?" }],
    comebackArcs: [{ id: "borealis-grid-awakens", title: "The Line Across the Ice", premise: "A regional transmission project finally reaches Borealis.", triggerTags: ["grid", "infrastructure", "macro"], beats: ["Funding is approved.", "Construction survives winter.", "The stranded asset gains a route to market."], unresolvedQuestion: "Has the wait created value, or merely removed one excuse?" }],
    legendaryEndings: [{ id: "borealis-reserve", title: "The Northern Reserve", legend: "Borealis becomes the region’s patient strategic backbone.", condition: "Preserve community trust, survive a full cycle, and complete the grid connection." }],
    hiddenEndings: [{ id: "borealis-covenant", title: "The Community’s Company", legend: "Local stakeholders become owners and protect the asset through future political cycles.", condition: "Discover the old agreement and choose shared ownership over maximum control." }],
    stakeholders: [{ name: "Northglass Community Council", role: "community", leverage: "Can withhold social consent.", tension: "Remembers an agreement previous owners ignored." }, { name: "Arctic Grid Directorate", role: "government", leverage: "Controls transmission funding.", tension: "Strategic urgency may override patient consultation." }],
    narrativeVariables: [{ id: "borealis-energy-security", variable: "energy security", condition: "Imports become unreliable.", consequence: "The asset becomes strategically urgent before infrastructure is ready.", affectedRelationships: ["bluepeak-minerals", "Arctic Grid Directorate"] }, { id: "borealis-community-trust", variable: "community trust", condition: "Development accelerates without consultation.", consequence: "Political support rises nationally while local consent collapses.", affectedRelationships: ["Northglass Community Council"] }],
    arcCategories: {},
    eventTriggers: [{ id: "borealis-community", when: "Political pressure or infrastructure expansion occurs.", storyBeat: "The hidden community agreement moves closer to the center of the story.", tags: ["community", "politics"] }],
  },
  "terranova-copper": {
    frameworkVersion: 2,
    identity: "A strategic prize learning whether it wants independence or rescue.",
    personalityArchetype: "empire",
    belief: "Control of a necessary asset is more valuable than early approval.",
    coreDesire: "Become too useful for a larger empire to ignore.",
    greatestStrength: "A scarce asset positioned inside a powerful long-term demand story.",
    fatalFlaw: "Takeover attention can substitute for proving the company can succeed alone.",
    companyCulture: "Diplomatic, ambitious, strategically patient, and intensely protective of independence.",
    investorExcitement: "Scarcity and strategic relevance can attract partners or acquirers with far deeper resources.",
    investorHesitation: "Management may prefer empire-building to accepting a rational outcome for current owners.",
    biggestCatalyst: "A processing milestone proves TerraNova does not require a rescuer.",
    biggestUnknown: "What price management already refused and why.",
    hiddenTruth: "Management has already rejected one credible offer without telling shareholders.",
    secretOpportunity: "A processing breakthrough could make TerraNova independent of outside infrastructure.",
    secretWeakness: "A key permit changes ownership terms after a takeover.",
    moralDilemma: "Accept a fair offer now or protect a larger future that current owners may never see.",
    longTermAmbition: "Build an independent strategic champion rather than become inventory for an empire.",
    fear: "Sell too early—or wait until strategic interest moves elsewhere.",
    founderStory: "A former diplomat assembled TerraNova by negotiating claims no single operator could secure, then promised never to sell cheaply.",
    currentChapter: "Strategic interest is rising before independent execution has been fully proven.",
    futurePossibilities: ["TerraNova becomes an independent major.", "A perfect sale rewards patience.", "A rejected offer becomes the high-water mark."],
    rivals: [{ companyId: "aurora-metals", relationship: "Builder credibility versus strategic scale", tension: "Both need the same corridor and attract the same potential acquirer." }],
    allies: [{ companyId: "silver-mammoth", relationship: "Optional satellite discovery", tension: "Mammoth can enlarge TerraNova’s district or consume its capital." }],
    relationshipHooks: ["Remember players who sell before a takeover.", "Let independence become more credible after execution wins.", "Create a choice between rescuing Mammoth and protecting TerraNova’s balance sheet."],
    macroTriggers: [{ id: "terranova-strategic-bid", when: "Supply security becomes urgent.", storyBeat: "Larger empires begin valuing control more than price discipline.", tags: ["takeover", "security", "commodity"] }],
    crisisArcs: [{ id: "terranova-hostile", title: "The Offer With Teeth", premise: "A larger empire makes an offer directly to owners.", triggerTags: ["takeover", "board", "rumor"], beats: ["The board rejects the approach.", "The hidden prior offer leaks.", "Owners must choose independence or certainty."], unresolvedQuestion: "Whose ambition is management protecting?" }],
    comebackArcs: [{ id: "terranova-alone", title: "Proof of Independence", premise: "A technical milestone removes the need for a rescue.", triggerTags: ["execution", "technology", "infrastructure"], beats: ["A pilot works.", "Financing terms improve.", "The bidder returns at a higher price."], unresolvedQuestion: "Does new strength justify remaining independent?" }],
    legendaryEndings: [{ id: "terranova-empire", title: "The Empire That Refused to Be Bought", legend: "TerraNova becomes the strategic major everyone expected to acquire it.", condition: "Reject an early offer, solve infrastructure, and complete independent development." }],
    hiddenEndings: [{ id: "terranova-perfect-sale", title: "The Price of Enough", legend: "TerraNova sells at the moment ambition and discipline finally agree.", condition: "Reveal the prior offer and accept a later bid after proving independent value." }],
    stakeholders: [{ name: "Coastal Strategic Metals Office", role: "regulator", leverage: "Can attach conditions to foreign ownership.", tension: "Wants domestic control without funding development." }, { name: "Atlas Smelting Combine", role: "customer", leverage: "Can validate future demand through an anchor contract.", tension: "Prefers TerraNova dependent and cheap." }],
    narrativeVariables: [{ id: "terranova-takeover-cycle", variable: "takeover appetite", condition: "A competitor fails or supply security rises.", consequence: "Strategic bids arrive before independent proof.", affectedRelationships: ["aurora-metals", "silver-mammoth"] }, { id: "terranova-independence", variable: "independent execution", condition: "Milestones complete without partner capital.", consequence: "Bid value rises while management becomes harder to persuade.", affectedRelationships: ["Atlas Smelting Combine"] }],
    arcCategories: {},
    eventTriggers: [{ id: "terranova-rumor-memory", when: "A takeover rumor appears.", storyBeat: "The company remembers whether the player previously treated it as a business or a lottery ticket.", tags: ["memory", "takeover"] }],
  },
  "emberrock-mining": {
    frameworkVersion: 2,
    identity: "A charismatic survivor that has mistaken another tomorrow for progress.",
    personalityArchetype: "survivor",
    belief: "As long as the company survives, redemption remains possible.",
    coreDesire: "Earn one genuine second chance after years of manufactured ones.",
    greatestStrength: "Management can keep stakeholders engaged when almost any other company would disappear.",
    fatalFlaw: "Survival tactics consume the capital and trust required for a real turnaround.",
    companyCulture: "Charismatic, improvisational, loyal to the founder, and practiced at reframing missed promises.",
    investorExcitement: "A deeply discounted collection of assets may contain one valuable core hidden by the crisis.",
    investorHesitation: "Repeated rescues have protected the institution more reliably than owners.",
    biggestCatalyst: "A new operator reveals and protects the profitable hidden asset.",
    biggestUnknown: "Whether management can surrender the grand story required for an honest recovery.",
    hiddenTruth: "One unfashionable asset is profitable, but management hides it inside the larger story.",
    secretOpportunity: "Selling the founder’s favorite project could fund a smaller, honest company.",
    secretWeakness: "A financing covenant transfers control after one more missed target.",
    moralDilemma: "Abandon the grand turnaround story to save the useful pieces.",
    longTermAmbition: "Become proof that a broken company can change its character.",
    fear: "Discover that everyone was right to stop believing.",
    founderStory: "The founder saved EmberRock from its first bankruptcy and has treated every later crisis as evidence that only he can save it again.",
    currentChapter: "Another financing request arrives with familiar promises and less remaining credibility.",
    futurePossibilities: ["A smaller honest company emerges.", "An orderly breakup saves useful pieces.", "One final rescue transfers control away from believers."],
    rivals: [{ companyId: "ironwood-resources", relationship: "Promotional ambition versus quiet discipline", tension: "EmberRock covets Ironwood’s customers and resents its credibility." }],
    allies: [{ companyId: "helio-rare-earths", relationship: "Potential royalty buyer", tension: "Helio can fund EmberRock by purchasing its best hidden asset at a painful price." }],
    relationshipHooks: ["Let research reveal the profitable hidden asset.", "Remember players who repeatedly finance promises.", "Make Ironwood’s discipline expose EmberRock’s excuses."],
    macroTriggers: [{ id: "emberrock-easy-money", when: "Capital becomes cheap and hype rises.", storyBeat: "EmberRock receives another chance without having to change.", tags: ["financing", "hype", "moral-hazard"] }],
    crisisArcs: [{ id: "emberrock-eighth-plan", title: "The Eighth Turnaround", premise: "Management requests one final financing under familiar language.", triggerTags: ["dilution", "management", "zombie"], beats: ["A new deck appears.", "The covenant is discovered.", "The profitable asset becomes visible."], unresolvedQuestion: "Can the company survive only by becoming smaller and less heroic?" }],
    comebackArcs: [{ id: "emberrock-honest", title: "The Honest Company", premise: "A new operator abandons the grand story and protects the useful core.", triggerTags: ["leadership", "restructuring", "research"], beats: ["The founder leaves.", "Assets are sold.", "The remaining operation reports a quiet profit."], unresolvedQuestion: "Will stakeholders accept a modest truth after years of magnificent promises?" }],
    legendaryEndings: [{ id: "emberrock-redeemed", title: "The Turnaround That Finally Was", legend: "EmberRock becomes valuable only after surrendering the identity it fought to preserve.", condition: "Reveal the hidden asset, remove the founder, and refuse one final dilutive rescue." }],
    hiddenEndings: [{ id: "emberrock-pieces", title: "Useful Ruins", legend: "EmberRock disappears, but its best people and assets strengthen three former rivals.", condition: "Choose an orderly breakup while credibility remains." }],
    stakeholders: [{ name: "Cinder Credit Partners", role: "supplier", leverage: "Controls the next refinancing.", tension: "Profits from survival, not recovery." }, { name: "EmberRock Founder Circle", role: "founder", leverage: "Controls the board narrative.", tension: "Treats removal as betrayal." }],
    narrativeVariables: [{ id: "emberrock-easy-capital", variable: "cost of capital", condition: "Financing becomes easy.", consequence: "EmberRock avoids change and extends the turnaround story.", affectedRelationships: ["Cinder Credit Partners"] }, { id: "emberrock-competitor-failure", variable: "competitor failure", condition: "Ironwood loses an anchor customer.", consequence: "EmberRock can capture share if operations are real enough.", affectedRelationships: ["ironwood-resources"] }],
    arcCategories: {},
    eventTriggers: [{ id: "emberrock-finance", when: "Financing closes after missed execution.", storyBeat: "Institutional Trust changes the terms offered to EmberRock.", tags: ["hidden-system", "financing"] }],
  },
  "bluepeak-minerals": {
    frameworkVersion: 2,
    identity: "A capable company whose destiny is held hostage by the map around it.",
    personalityArchetype: "engineer",
    belief: "Infrastructure is not background; it is part of the asset.",
    coreDesire: "Secure the single practical connection that makes the asset real.",
    greatestStrength: "Management understands the project and has resisted exaggerating what it controls.",
    fatalFlaw: "The company can execute perfectly and still lose to infrastructure outside its authority.",
    companyCulture: "Practical, collaborative, systems-oriented, and uncomfortable with promises it cannot engineer directly.",
    investorExcitement: "One shared connection can transform both project economics and an entire regional corridor.",
    investorHesitation: "Value depends on governments and partners whose timelines BluePeak cannot control.",
    biggestCatalyst: "A funded corridor agreement aligns water, road, and power access.",
    biggestUnknown: "How much ownership BluePeak must surrender to make cooperation possible.",
    hiddenTruth: "A cheaper water route exists, but it would require cooperation with a political rival.",
    secretOpportunity: "Shared infrastructure with Borealis could unlock an entire corridor.",
    secretWeakness: "Its current access agreement expires before expected construction completion.",
    moralDilemma: "Share control and value with the region or preserve ownership of a stranded asset.",
    longTermAmbition: "Transform an isolated project into the anchor of a new economic corridor.",
    fear: "Do everything right and remain impossible to reach.",
    founderStory: "A civil engineer founded BluePeak after watching technically strong projects fail because nobody treated roads and water as part of the asset.",
    currentChapter: "The project is credible, but access rights may expire before the surrounding world is ready.",
    futurePossibilities: ["BluePeak moves the map for everyone.", "The network becomes more valuable than extraction.", "A technically sound project remains stranded."],
    rivals: [{ companyId: "terranova-copper", relationship: "Competing corridor priority", tension: "TerraNova can outbid BluePeak for access but needs BluePeak’s water design." }],
    allies: [{ companyId: "borealis-energy", relationship: "Shared corridor economics", tension: "Each project makes the other viable, but neither wants to fund the first move alone." }],
    relationshipHooks: ["Tie Borealis events to BluePeak’s infrastructure odds.", "Reward credibility spent on regional cooperation.", "Remember players who blamed management for external delays."],
    macroTriggers: [{ id: "bluepeak-public-works", when: "Infrastructure funding expands.", storyBeat: "A public decision changes BluePeak more than any discovery could.", tags: ["infrastructure", "policy", "region"] }],
    crisisArcs: [{ id: "bluepeak-expiring-road", title: "The Road That Closes First", premise: "Access rights expire before the project is ready.", triggerTags: ["permit", "delay", "infrastructure"], beats: ["The timeline slips.", "TerraNova seeks priority.", "The region demands shared ownership."], unresolvedQuestion: "How much value should BluePeak surrender to become real?" }],
    comebackArcs: [{ id: "bluepeak-shared-corridor", title: "The Map Learns Cooperation", premise: "BluePeak and Borealis combine their infrastructure plans.", triggerTags: ["ally", "credibility", "infrastructure"], beats: ["Engineers share designs.", "The region funds the connection.", "Both stranded assets gain a path forward."], unresolvedQuestion: "Can cooperation survive once value becomes visible?" }],
    legendaryEndings: [{ id: "bluepeak-corridor", title: "The Company That Moved the Map", legend: "BluePeak becomes the reason an entire region can build.", condition: "Form the Borealis alliance, preserve regional trust, and complete shared infrastructure." }],
    hiddenEndings: [{ id: "bluepeak-utility", title: "The Asset Was the Network", legend: "BluePeak abandons extraction and becomes the corridor’s enduring utility.", condition: "Discover the cheaper route and choose infrastructure ownership over the original project." }],
    stakeholders: [{ name: "Desert Water Compact", role: "regulator", leverage: "Controls shared water rights.", tension: "Demands regional access in exchange for approval." }, { name: "Solis Transmission Works", role: "supplier", leverage: "Can build the line neither project can justify alone.", tension: "Needs Borealis and BluePeak to commit together." }],
    narrativeVariables: [{ id: "bluepeak-shared-infrastructure", variable: "ally commitment", condition: "Borealis secures policy support.", consequence: "BluePeak’s connection becomes financeable.", affectedRelationships: ["borealis-energy", "Solis Transmission Works"] }, { id: "bluepeak-access-expiry", variable: "access timeline", condition: "Two delays occur before renewal.", consequence: "TerraNova can claim corridor priority.", affectedRelationships: ["terranova-copper"] }],
    arcCategories: {},
    eventTriggers: [{ id: "bluepeak-borealis-link", when: "Borealis receives an infrastructure breakthrough or failure.", storyBeat: "BluePeak’s economics change in sympathy.", tags: ["ally", "ecosystem"] }],
  },
  "helio-rare-earths": {
    frameworkVersion: 2,
    identity: "A quiet holder of indirect power hidden inside contracts others overlook.",
    personalityArchetype: "opportunist",
    belief: "The smallest contractual right can control the largest future value.",
    coreDesire: "Be recognized as an allocator of leverage rather than a small project company.",
    greatestStrength: "Management sees value in rights, royalties, and clauses before others understand them.",
    fatalFlaw: "Complexity can hide weak assets as easily as it hides extraordinary ones.",
    companyCulture: "Analytical, discreet, legally inventive, and unusually sensitive to reputation among private counterparties.",
    investorExcitement: "A diversified set of overlooked claims can create upside without funding every underlying project.",
    investorHesitation: "Legal interpretation and opaque valuation may support more of the thesis than operating evidence.",
    biggestCatalyst: "The first meaningful royalty payment proves the model in cash.",
    biggestUnknown: "Whether the most valuable clause survives a change of control.",
    hiddenTruth: "Its most valuable clause may be invalid after a change of control.",
    secretOpportunity: "EmberRock’s profitable hidden asset could be acquired cheaply as a royalty.",
    secretWeakness: "One legal interpretation supports most of the company’s stated optionality.",
    moralDilemma: "Exploit counterparties who misunderstand their contracts or preserve the trust that creates future deals.",
    longTermAmbition: "Build an invisible empire of claims on other companies’ success.",
    fear: "Have the market finally understand the structure—and discover there was less inside than imagined.",
    founderStory: "A former project lawyer founded Helio after realizing the smallest paragraph in a contract sometimes controlled the largest future cash flow.",
    currentChapter: "The portfolio looks modest while takeover activity moves several hidden claims toward a test.",
    futurePossibilities: ["An invisible empire of royalties emerges.", "Fair dealing unlocks trusted private opportunities.", "One legal ruling exposes concentrated fragility."],
    rivals: [{ companyId: "terranova-copper", relationship: "Contract leverage versus strategic control", tension: "TerraNova wants to eliminate Helio’s claim before accepting a takeover." }],
    allies: [{ companyId: "ironwood-resources", relationship: "Trusted quiet counterparty", tension: "Ironwood provides credibility, but refuses clever terms it considers unfair." }],
    relationshipHooks: ["Let legal research reveal hidden endings.", "Make trust affect access to private contracts.", "Offer EmberRock’s hidden asset after its crisis deepens."],
    macroTriggers: [{ id: "helio-consolidation", when: "Takeovers spread across the ecosystem.", storyBeat: "Every acquisition tests whether Helio’s quiet claims survive ownership changes.", tags: ["takeover", "contracts", "optionality"] }],
    crisisArcs: [{ id: "helio-clause", title: "The Clause That Vanished", premise: "A legal challenge attacks Helio’s most valuable hidden right.", triggerTags: ["legal", "takeover", "hidden-truth"], beats: ["A buyer disputes the claim.", "The original drafter is found.", "Management must settle or risk everything in court."], unresolvedQuestion: "Is complexity Helio’s moat—or the fog protecting a fragile thesis?" }],
    comebackArcs: [{ id: "helio-portfolio", title: "A Thousand Small Claims", premise: "Helio diversifies away from the disputed clause through disciplined acquisitions.", triggerTags: ["allocator", "trust", "contracts"], beats: ["One royalty pays out.", "Institutions offer private deals.", "No single clause controls the future."], unresolvedQuestion: "Can hidden leverage remain attractive after it becomes an institution?" }],
    legendaryEndings: [{ id: "helio-invisible-empire", title: "The Invisible Empire", legend: "Helio owns no celebrated project and participates in every important one.", condition: "Preserve Institutional Trust, diversify contracts, and survive a legal challenge." }],
    hiddenEndings: [{ id: "helio-fair-dealing", title: "The Clause Returned", legend: "Helio surrenders an unfair claim and receives a generation of trusted opportunities in return.", condition: "Discover the moral dilemma and choose reputation over maximum legal leverage." }],
    stakeholders: [{ name: "Lumen Contract Court", role: "regulator", leverage: "Sets precedent for disputed clauses.", tension: "Values clarity more than Helio’s clever interpretation." }, { name: "Quiet Capital Consortium", role: "customer", leverage: "Offers private royalty opportunities.", tension: "Withdraws access if Helio exploits counterparties." }],
    narrativeVariables: [{ id: "helio-trust-variable", variable: "institutional trust", condition: "The player behaves consistently across runs.", consequence: "Private counterparties offer higher-quality contracts.", affectedRelationships: ["Quiet Capital Consortium", "ironwood-resources"] }, { id: "helio-takeover-variable", variable: "ecosystem consolidation", condition: "TerraNova or EmberRock changes control.", consequence: "Helio’s clauses either crystallize or face legal challenge.", affectedRelationships: ["terranova-copper", "emberrock-mining"] }],
    arcCategories: {},
    eventTriggers: [{ id: "helio-trust-market", when: "Institutional Trust is discovered.", storyBeat: "Private counterparties begin offering Helio opportunities before public auctions.", tags: ["hidden-system", "trust", "opportunity"] }],
  },
};
