import type { CompanyNarrative } from "../types";

export const companyNarratives: Record<string, CompanyNarrative> = {
  "aurora-metals": {
    identity: "A celebrated veteran team attempting one final impossible build.",
    coreDesire: "Prove that hard-earned craft still matters more than fashionable storytelling.",
    greatestStrength: "The team has finished difficult projects before and understands what failure looks like up close.",
    fatalFlaw: "Past success makes leadership slow to recognize when the present is fundamentally different.",
    hiddenTruth: "The famous founder is no longer making the most important operating decisions.",
    secretOpportunity: "A deeper zone could extend the district into a multi-generation asset.",
    secretWeakness: "Several senior operators may retire before construction reaches its hardest stage.",
    moralDilemma: "Protect the old team’s legacy or replace loyal veterans with people suited to the new reality.",
    longTermAmbition: "Build a district that outlives every person currently leading it.",
    fear: "Be remembered as builders who stayed one project too long.",
    founderStory: "Mara Vale earned her reputation rebuilding a mine everyone else had abandoned; Aurora is the promise she made to prove it was skill, not luck.",
    rivals: [{ companyId: "terranova-copper", relationship: "Competing claim to strategic infrastructure", tension: "Only one project may receive priority access through the mountain corridor." }],
    allies: [{ companyId: "bluepeak-minerals", relationship: "Shared engineering culture", tension: "BluePeak can solve Aurora’s access problem, but expects influence in return." }],
    relationshipHooks: ["Reward patience after a construction delay.", "Remember players who replace the founder’s loyal team.", "Offer TerraNova’s takeover interest after Aurora appears weak."],
    macroTriggers: [
      { id: "aurora-metal-cycle", when: "Commodity demand rises while construction remains unfinished.", storyBeat: "The market rewards Aurora before the mine proves it can operate.", tags: ["commodity-boom", "hype", "construction"] },
      { id: "aurora-cost-regime", when: "Cost inflation arrives with a weak balance sheet.", storyBeat: "Experience cannot negotiate with every rising input at once.", tags: ["inflation", "financing", "crisis"] },
    ],
    crisisArcs: [
      { id: "aurora-last-build", title: "The Last Build", premise: "A serious delay forces the veterans to choose between pride and outside help.", triggerTags: ["delay", "execution", "founder"], beats: ["The schedule slips.", "A younger operator challenges the plan.", "The founder must surrender control or double down."], unresolvedQuestion: "Can a great builder remain great by admitting the old method no longer works?" },
      { id: "aurora-succession", title: "Empty Chair at the Summit", premise: "The founder’s health makes succession unavoidable.", triggerTags: ["leadership", "retirement"], beats: ["Rumors spread.", "Two successors emerge.", "Loyalty divides the operating team."], unresolvedQuestion: "Is Aurora an institution or a biography?" },
    ],
    comebackArcs: [{ id: "aurora-first-pour", title: "The Furnace Answers", premise: "After repeated delays, the first production proves the team still knows how to finish.", triggerTags: ["hold", "execution", "recovery"], beats: ["The final bottleneck clears.", "Costs stabilize.", "The first shipment leaves the valley."], unresolvedQuestion: "Was the victory repeatable, or the last act of an exceptional generation?" }],
    legendaryEndings: [{ id: "aurora-cathedral", title: "The Cathedral in the Mountain", legend: "Aurora becomes the district every future builder studies.", condition: "Back Aurora through multiple crises and preserve both execution quality and institutional succession." }],
    hiddenEndings: [{ id: "aurora-teacher", title: "The Builders Who Walked Away", legend: "Aurora sells the deposit and turns its veteran team into a school for the next generation.", condition: "Discover the succession truth, reject empire, and accept a disciplined takeover." }],
    eventTriggers: [
      { id: "aurora-delay-memory", when: "A permitting or construction delay occurs.", storyBeat: "Aurora remembers whether the player held, researched, or abandoned it.", tags: ["memory", "delay"] },
      { id: "aurora-takeover-choice", when: "A takeover rumor follows visible weakness.", storyBeat: "TerraNova’s advisers quietly enter the valley.", tags: ["takeover", "rival"] },
    ],
  },
  "ironwood-resources": {
    identity: "The unfashionable provider that keeps working while louder stories collapse.",
    coreDesire: "Be valued for durability without becoming something it is not.",
    greatestStrength: "Reliable cash generation and disciplined operations.",
    fatalFlaw: "Caution can harden into complacency and starve the future.",
    hiddenTruth: "Its oldest customer is quietly preparing to leave.",
    secretOpportunity: "Its logistics network could become more valuable than the mine itself.",
    secretWeakness: "Management has postponed replacement investment for too long.",
    moralDilemma: "Return cash to loyal owners or reinvest before the old operation begins to decay.",
    longTermAmbition: "Become the indispensable quiet infrastructure behind an entire region.",
    fear: "Wake up profitable, respected, and suddenly obsolete.",
    founderStory: "Two siblings bought unwanted equipment after a bankruptcy and built Ironwood by refusing every fashionable expansion.",
    rivals: [{ companyId: "emberrock-mining", relationship: "Low-cost discipline versus endless turnaround", tension: "EmberRock wants Ironwood’s customers and calls its caution cowardice." }],
    allies: [{ companyId: "helio-rare-earths", relationship: "Quiet contractual partners", tension: "Helio’s hidden license can protect Ironwood’s margins if both sides trust the other." }],
    relationshipHooks: ["Reward players who notice maintenance before a breakdown.", "Reference missed growth when optionality is repeatedly ignored.", "Let EmberRock poach customers after Ironwood becomes complacent."],
    macroTriggers: [{ id: "ironwood-recession", when: "A broad downturn punishes fragile companies.", storyBeat: "Ironwood’s boring contracts become a form of power.", tags: ["recession", "cash-flow", "durability"] }],
    crisisArcs: [{ id: "ironwood-anchor-leaves", title: "The Silent Customer", premise: "The customer that built Ironwood’s stability declines to renew.", triggerTags: ["customer", "cash-flow", "hidden-truth"], beats: ["Volumes soften.", "Management denies concentration risk.", "A rival offers to buy the logistics network."], unresolvedQuestion: "Was Ironwood durable, or merely dependent?" }],
    comebackArcs: [{ id: "ironwood-second-engine", title: "The Boring Reinvention", premise: "Ironwood turns its neglected logistics network into a second business.", triggerTags: ["infrastructure", "reinvestment"], beats: ["A pilot contract appears.", "Old equipment finds a new purpose.", "The market notices recurring revenue."], unresolvedQuestion: "Can reinvention remain disciplined once attention arrives?" }],
    legendaryEndings: [{ id: "ironwood-compounder", title: "The Hundred Quiet Quarters", legend: "Ironwood compounds for a generation without needing to become famous.", condition: "Protect maintenance, diversify customers, and resist a hype-driven expansion." }],
    hiddenEndings: [{ id: "ironwood-public-road", title: "The Company That Became a Road", legend: "Ironwood spins out its network as shared infrastructure and outlives its original mine.", condition: "Discover the logistics opportunity and choose regional usefulness over extraction growth." }],
    eventTriggers: [{ id: "ironwood-maintenance", when: "Infrastructure weakens or costs rise.", storyBeat: "Deferred maintenance stops being invisible.", tags: ["maintenance", "costs"] }],
  },
  "silver-mammoth": {
    identity: "A breathtaking possibility carried by a company too fragile to deserve certainty.",
    coreDesire: "Find enough proof before the treasury runs out.",
    greatestStrength: "An unusually large potential discovery with multiple ways to surprise the world.",
    fatalFlaw: "Every promising signal encourages spending as though success were already proven.",
    hiddenTruth: "The best result may sit across a boundary the company does not control.",
    secretOpportunity: "A larger geological system could make Mammoth strategically unavoidable.",
    secretWeakness: "The next financing gives a promoter effective control over the company.",
    moralDilemma: "Dilute early believers to keep exploring or stop before the answer is known.",
    longTermAmbition: "Make the discovery that redraws the frontier.",
    fear: "Become a famous chart attached to a deposit that never becomes a mine.",
    founderStory: "A field geologist mortgaged everything after finding one impossible sample and has spent a decade trying to prove it was not an accident.",
    rivals: [{ companyId: "aurora-metals", relationship: "Dreamer versus builder", tension: "Aurora dismisses Mammoth as geology without a path to construction." }],
    allies: [{ companyId: "terranova-copper", relationship: "Potential strategic rescuer", tension: "TerraNova can fund the answer but may take the discovery from early believers." }],
    relationshipHooks: ["Remember who believed before proof.", "Punish blind loyalty after repeated dilution.", "Let Aurora’s experts validate or reject the discovery."],
    macroTriggers: [{ id: "mammoth-silver-fever", when: "Commodity prices and market hype rise together.", storyBeat: "Mammoth can finance easily, but truth becomes harder to hear beneath excitement.", tags: ["boom", "hype", "financing"] }],
    crisisArcs: [{ id: "mammoth-last-hole", title: "The Last Hole", premise: "The treasury can fund one final test.", triggerTags: ["dry-hole", "financing", "geology"], beats: ["The board chooses a target.", "A rival interpretation emerges.", "The drill enters the unknown."], unresolvedQuestion: "Is conviction courage when the evidence is incomplete—or denial when the treasury is empty?" }],
    comebackArcs: [{ id: "mammoth-deeper", title: "Deeper Than Doubt", premise: "A follow-up result reveals the failed test stopped just short of the real system.", triggerTags: ["discovery", "research", "near-miss"], beats: ["Old data is re-read.", "A deeper target forms.", "The market returns reluctantly."], unresolvedQuestion: "Will the second chance create discipline or restart the same fever?" }],
    legendaryEndings: [{ id: "mammoth-world-class", title: "The Mammoth Beneath the Dust", legend: "The frontier discovery becomes a world-scale district.", condition: "Fund disciplined research, survive dilution, and reveal exceptional geology." }],
    hiddenEndings: [{ id: "mammoth-walk-away", title: "The Hole Not Drilled", legend: "The company returns its remaining cash rather than sell one more dream.", condition: "Reveal weak control and choose intellectual honesty over another financing." }],
    eventTriggers: [{ id: "mammoth-financing-memory", when: "Financing follows a major discovery or failure.", storyBeat: "The terms depend on whether the player previously rewarded promotion or demanded evidence.", tags: ["memory", "dilution"] }],
  },
  "borealis-energy": {
    identity: "A stranded strategic asset waiting for history to need it again.",
    coreDesire: "Survive long enough for the energy cycle to return.",
    greatestStrength: "Scarce strategic exposure that cannot be recreated quickly.",
    fatalFlaw: "Being early feels indistinguishable from being wrong for long stretches of time.",
    hiddenTruth: "A local community holds an old agreement that can stop expansion.",
    secretOpportunity: "A neighboring grid project could transform the asset’s economics overnight.",
    secretWeakness: "Cold-weather infrastructure requires more replacement capital than public estimates admit.",
    moralDilemma: "Push development during a strategic shortage or renegotiate patiently with the people who live there.",
    longTermAmbition: "Become the stable energy reserve a vulnerable region cannot do without.",
    fear: "Run out of patience one season before the world finally changes.",
    founderStory: "Borealis began when a former grid planner bought rights nobody wanted after a policy reversal and refused to sell them back cheaply.",
    rivals: [{ companyId: "terranova-copper", relationship: "Competing strategic priority", tension: "Governments may fund electrification metals or energy security first, but not both." }],
    allies: [{ companyId: "bluepeak-minerals", relationship: "Shared transmission destiny", tension: "A successful corridor unlocks both companies; failure strands them together." }],
    relationshipHooks: ["Reward players who distinguish cycle patience from passive hope.", "Make community trust respond to credibility decisions.", "Tie BluePeak infrastructure outcomes to Borealis economics."],
    macroTriggers: [{ id: "borealis-security-shock", when: "Energy security becomes politically urgent.", storyBeat: "Borealis changes from forgotten inventory into strategic leverage.", tags: ["energy", "security", "policy"] }],
    crisisArcs: [{ id: "borealis-frozen-road", title: "The Winter That Did Not End", premise: "Infrastructure failure removes an entire operating season.", triggerTags: ["arctic", "infrastructure", "delay"], beats: ["The road closes.", "Cash burn accelerates.", "A government rescue arrives with conditions."], unresolvedQuestion: "Does strategic importance protect owners—or only the asset?" }],
    comebackArcs: [{ id: "borealis-grid-awakens", title: "The Line Across the Ice", premise: "A regional transmission project finally reaches Borealis.", triggerTags: ["grid", "infrastructure", "macro"], beats: ["Funding is approved.", "Construction survives winter.", "The stranded asset gains a route to market."], unresolvedQuestion: "Has the wait created value, or merely removed one excuse?" }],
    legendaryEndings: [{ id: "borealis-reserve", title: "The Northern Reserve", legend: "Borealis becomes the region’s patient strategic backbone.", condition: "Preserve community trust, survive a full cycle, and complete the grid connection." }],
    hiddenEndings: [{ id: "borealis-covenant", title: "The Community’s Company", legend: "Local stakeholders become owners and protect the asset through future political cycles.", condition: "Discover the old agreement and choose shared ownership over maximum control." }],
    eventTriggers: [{ id: "borealis-community", when: "Political pressure or infrastructure expansion occurs.", storyBeat: "The hidden community agreement moves closer to the center of the story.", tags: ["community", "politics"] }],
  },
  "terranova-copper": {
    identity: "A strategic prize learning whether it wants independence or rescue.",
    coreDesire: "Become too useful for a larger empire to ignore.",
    greatestStrength: "A scarce asset positioned inside a powerful long-term demand story.",
    fatalFlaw: "Takeover attention can substitute for proving the company can succeed alone.",
    hiddenTruth: "Management has already rejected one credible offer without telling shareholders.",
    secretOpportunity: "A processing breakthrough could make TerraNova independent of outside infrastructure.",
    secretWeakness: "A key permit changes ownership terms after a takeover.",
    moralDilemma: "Accept a fair offer now or protect a larger future that current owners may never see.",
    longTermAmbition: "Build an independent strategic champion rather than become inventory for an empire.",
    fear: "Sell too early—or wait until strategic interest moves elsewhere.",
    founderStory: "A former diplomat assembled TerraNova by negotiating claims no single operator could secure, then promised never to sell cheaply.",
    rivals: [{ companyId: "aurora-metals", relationship: "Builder credibility versus strategic scale", tension: "Both need the same corridor and attract the same potential acquirer." }],
    allies: [{ companyId: "silver-mammoth", relationship: "Optional satellite discovery", tension: "Mammoth can enlarge TerraNova’s district or consume its capital." }],
    relationshipHooks: ["Remember players who sell before a takeover.", "Let independence become more credible after execution wins.", "Create a choice between rescuing Mammoth and protecting TerraNova’s balance sheet."],
    macroTriggers: [{ id: "terranova-strategic-bid", when: "Supply security becomes urgent.", storyBeat: "Larger empires begin valuing control more than price discipline.", tags: ["takeover", "security", "commodity"] }],
    crisisArcs: [{ id: "terranova-hostile", title: "The Offer With Teeth", premise: "A larger empire makes an offer directly to owners.", triggerTags: ["takeover", "board", "rumor"], beats: ["The board rejects the approach.", "The hidden prior offer leaks.", "Owners must choose independence or certainty."], unresolvedQuestion: "Whose ambition is management protecting?" }],
    comebackArcs: [{ id: "terranova-alone", title: "Proof of Independence", premise: "A technical milestone removes the need for a rescue.", triggerTags: ["execution", "technology", "infrastructure"], beats: ["A pilot works.", "Financing terms improve.", "The bidder returns at a higher price."], unresolvedQuestion: "Does new strength justify remaining independent?" }],
    legendaryEndings: [{ id: "terranova-empire", title: "The Empire That Refused to Be Bought", legend: "TerraNova becomes the strategic major everyone expected to acquire it.", condition: "Reject an early offer, solve infrastructure, and complete independent development." }],
    hiddenEndings: [{ id: "terranova-perfect-sale", title: "The Price of Enough", legend: "TerraNova sells at the moment ambition and discipline finally agree.", condition: "Reveal the prior offer and accept a later bid after proving independent value." }],
    eventTriggers: [{ id: "terranova-rumor-memory", when: "A takeover rumor appears.", storyBeat: "The company remembers whether the player previously treated it as a business or a lottery ticket.", tags: ["memory", "takeover"] }],
  },
  "emberrock-mining": {
    identity: "A charismatic survivor that has mistaken another tomorrow for progress.",
    coreDesire: "Earn one genuine second chance after years of manufactured ones.",
    greatestStrength: "Management can keep stakeholders engaged when almost any other company would disappear.",
    fatalFlaw: "Survival tactics consume the capital and trust required for a real turnaround.",
    hiddenTruth: "One unfashionable asset is profitable, but management hides it inside the larger story.",
    secretOpportunity: "Selling the founder’s favorite project could fund a smaller, honest company.",
    secretWeakness: "A financing covenant transfers control after one more missed target.",
    moralDilemma: "Abandon the grand turnaround story to save the useful pieces.",
    longTermAmbition: "Become proof that a broken company can change its character.",
    fear: "Discover that everyone was right to stop believing.",
    founderStory: "The founder saved EmberRock from its first bankruptcy and has treated every later crisis as evidence that only he can save it again.",
    rivals: [{ companyId: "ironwood-resources", relationship: "Promotional ambition versus quiet discipline", tension: "EmberRock covets Ironwood’s customers and resents its credibility." }],
    allies: [{ companyId: "helio-rare-earths", relationship: "Potential royalty buyer", tension: "Helio can fund EmberRock by purchasing its best hidden asset at a painful price." }],
    relationshipHooks: ["Let research reveal the profitable hidden asset.", "Remember players who repeatedly finance promises.", "Make Ironwood’s discipline expose EmberRock’s excuses."],
    macroTriggers: [{ id: "emberrock-easy-money", when: "Capital becomes cheap and hype rises.", storyBeat: "EmberRock receives another chance without having to change.", tags: ["financing", "hype", "moral-hazard"] }],
    crisisArcs: [{ id: "emberrock-eighth-plan", title: "The Eighth Turnaround", premise: "Management requests one final financing under familiar language.", triggerTags: ["dilution", "management", "zombie"], beats: ["A new deck appears.", "The covenant is discovered.", "The profitable asset becomes visible."], unresolvedQuestion: "Can the company survive only by becoming smaller and less heroic?" }],
    comebackArcs: [{ id: "emberrock-honest", title: "The Honest Company", premise: "A new operator abandons the grand story and protects the useful core.", triggerTags: ["leadership", "restructuring", "research"], beats: ["The founder leaves.", "Assets are sold.", "The remaining operation reports a quiet profit."], unresolvedQuestion: "Will stakeholders accept a modest truth after years of magnificent promises?" }],
    legendaryEndings: [{ id: "emberrock-redeemed", title: "The Turnaround That Finally Was", legend: "EmberRock becomes valuable only after surrendering the identity it fought to preserve.", condition: "Reveal the hidden asset, remove the founder, and refuse one final dilutive rescue." }],
    hiddenEndings: [{ id: "emberrock-pieces", title: "Useful Ruins", legend: "EmberRock disappears, but its best people and assets strengthen three former rivals.", condition: "Choose an orderly breakup while credibility remains." }],
    eventTriggers: [{ id: "emberrock-finance", when: "Financing closes after missed execution.", storyBeat: "Institutional Trust changes the terms offered to EmberRock.", tags: ["hidden-system", "financing"] }],
  },
  "bluepeak-minerals": {
    identity: "A capable company whose destiny is held hostage by the map around it.",
    coreDesire: "Secure the single practical connection that makes the asset real.",
    greatestStrength: "Management understands the project and has resisted exaggerating what it controls.",
    fatalFlaw: "The company can execute perfectly and still lose to infrastructure outside its authority.",
    hiddenTruth: "A cheaper water route exists, but it would require cooperation with a political rival.",
    secretOpportunity: "Shared infrastructure with Borealis could unlock an entire corridor.",
    secretWeakness: "Its current access agreement expires before expected construction completion.",
    moralDilemma: "Share control and value with the region or preserve ownership of a stranded asset.",
    longTermAmbition: "Transform an isolated project into the anchor of a new economic corridor.",
    fear: "Do everything right and remain impossible to reach.",
    founderStory: "A civil engineer founded BluePeak after watching technically strong projects fail because nobody treated roads and water as part of the asset.",
    rivals: [{ companyId: "terranova-copper", relationship: "Competing corridor priority", tension: "TerraNova can outbid BluePeak for access but needs BluePeak’s water design." }],
    allies: [{ companyId: "borealis-energy", relationship: "Shared corridor economics", tension: "Each project makes the other viable, but neither wants to fund the first move alone." }],
    relationshipHooks: ["Tie Borealis events to BluePeak’s infrastructure odds.", "Reward credibility spent on regional cooperation.", "Remember players who blamed management for external delays."],
    macroTriggers: [{ id: "bluepeak-public-works", when: "Infrastructure funding expands.", storyBeat: "A public decision changes BluePeak more than any discovery could.", tags: ["infrastructure", "policy", "region"] }],
    crisisArcs: [{ id: "bluepeak-expiring-road", title: "The Road That Closes First", premise: "Access rights expire before the project is ready.", triggerTags: ["permit", "delay", "infrastructure"], beats: ["The timeline slips.", "TerraNova seeks priority.", "The region demands shared ownership."], unresolvedQuestion: "How much value should BluePeak surrender to become real?" }],
    comebackArcs: [{ id: "bluepeak-shared-corridor", title: "The Map Learns Cooperation", premise: "BluePeak and Borealis combine their infrastructure plans.", triggerTags: ["ally", "credibility", "infrastructure"], beats: ["Engineers share designs.", "The region funds the connection.", "Both stranded assets gain a path forward."], unresolvedQuestion: "Can cooperation survive once value becomes visible?" }],
    legendaryEndings: [{ id: "bluepeak-corridor", title: "The Company That Moved the Map", legend: "BluePeak becomes the reason an entire region can build.", condition: "Form the Borealis alliance, preserve regional trust, and complete shared infrastructure." }],
    hiddenEndings: [{ id: "bluepeak-utility", title: "The Asset Was the Network", legend: "BluePeak abandons extraction and becomes the corridor’s enduring utility.", condition: "Discover the cheaper route and choose infrastructure ownership over the original project." }],
    eventTriggers: [{ id: "bluepeak-borealis-link", when: "Borealis receives an infrastructure breakthrough or failure.", storyBeat: "BluePeak’s economics change in sympathy.", tags: ["ally", "ecosystem"] }],
  },
  "helio-rare-earths": {
    identity: "A quiet holder of indirect power hidden inside contracts others overlook.",
    coreDesire: "Be recognized as an allocator of leverage rather than a small project company.",
    greatestStrength: "Management sees value in rights, royalties, and clauses before others understand them.",
    fatalFlaw: "Complexity can hide weak assets as easily as it hides extraordinary ones.",
    hiddenTruth: "Its most valuable clause may be invalid after a change of control.",
    secretOpportunity: "EmberRock’s profitable hidden asset could be acquired cheaply as a royalty.",
    secretWeakness: "One legal interpretation supports most of the company’s stated optionality.",
    moralDilemma: "Exploit counterparties who misunderstand their contracts or preserve the trust that creates future deals.",
    longTermAmbition: "Build an invisible empire of claims on other companies’ success.",
    fear: "Have the market finally understand the structure—and discover there was less inside than imagined.",
    founderStory: "A former project lawyer founded Helio after realizing the smallest paragraph in a contract sometimes controlled the largest future cash flow.",
    rivals: [{ companyId: "terranova-copper", relationship: "Contract leverage versus strategic control", tension: "TerraNova wants to eliminate Helio’s claim before accepting a takeover." }],
    allies: [{ companyId: "ironwood-resources", relationship: "Trusted quiet counterparty", tension: "Ironwood provides credibility, but refuses clever terms it considers unfair." }],
    relationshipHooks: ["Let legal research reveal hidden endings.", "Make trust affect access to private contracts.", "Offer EmberRock’s hidden asset after its crisis deepens."],
    macroTriggers: [{ id: "helio-consolidation", when: "Takeovers spread across the ecosystem.", storyBeat: "Every acquisition tests whether Helio’s quiet claims survive ownership changes.", tags: ["takeover", "contracts", "optionality"] }],
    crisisArcs: [{ id: "helio-clause", title: "The Clause That Vanished", premise: "A legal challenge attacks Helio’s most valuable hidden right.", triggerTags: ["legal", "takeover", "hidden-truth"], beats: ["A buyer disputes the claim.", "The original drafter is found.", "Management must settle or risk everything in court."], unresolvedQuestion: "Is complexity Helio’s moat—or the fog protecting a fragile thesis?" }],
    comebackArcs: [{ id: "helio-portfolio", title: "A Thousand Small Claims", premise: "Helio diversifies away from the disputed clause through disciplined acquisitions.", triggerTags: ["allocator", "trust", "contracts"], beats: ["One royalty pays out.", "Institutions offer private deals.", "No single clause controls the future."], unresolvedQuestion: "Can hidden leverage remain attractive after it becomes an institution?" }],
    legendaryEndings: [{ id: "helio-invisible-empire", title: "The Invisible Empire", legend: "Helio owns no celebrated project and participates in every important one.", condition: "Preserve Institutional Trust, diversify contracts, and survive a legal challenge." }],
    hiddenEndings: [{ id: "helio-fair-dealing", title: "The Clause Returned", legend: "Helio surrenders an unfair claim and receives a generation of trusted opportunities in return.", condition: "Discover the moral dilemma and choose reputation over maximum legal leverage." }],
    eventTriggers: [{ id: "helio-trust-market", when: "Institutional Trust is discovered.", storyBeat: "Private counterparties begin offering Helio opportunities before public auctions.", tags: ["hidden-system", "trust", "opportunity"] }],
  },
};
