import type { GameEvent } from "../types";

export const events: GameEvent[] = [
  { id: "drill-surprise", title: "Discovery Moment", kicker: "THE ROCK SPEAKS", description: "A hidden layer answers back. Doubt turns into possibility faster than anyone can process.", tone: "positive", targets: "one", effects: [{ trait: "geologicalLuck", traitDelta: 1, priceDelta: 0.24 }], narrative: "{company} reveals a deeper self. The world suddenly treats old uncertainty as new promise." },
  { id: "commodity-boom", title: "Cycle Awakens", kicker: "EVERYTHING HAS A BID", description: "The broader world remembers it needs raw materials, and sleepy characters wake with leverage.", tone: "positive", targets: "commodity", commodity: "Copper", effects: [{ trait: "commodityExposure", traitDelta: 1, priceDelta: 0.16 }], narrative: "Copper-linked characters catch a broad cyclical wind. Exposure becomes genius—temporarily." },
  { id: "union-strike", title: "The Gates Close", kicker: "THE PEOPLE PUSH BACK", description: "A human system refuses to behave like a line item. Execution gets tested in public.", tone: "negative", targets: "one", effects: [{ trait: "executionSkill", traitDelta: -1, priceDelta: -0.17 }], narrative: "{company} loses time and credibility as negotiation hardens into consequence." },
  { id: "financing-closed", title: "Runway Bought", kicker: "DILUTION SHOCK", description: "Survival improves, but the cost lands on everyone who believed early.", tone: "mixed", targets: "one", effects: [{ trait: "balanceSheet", traitDelta: 2, priceDelta: -0.06 }], narrative: "{company} buys time at a painful cost. Optionality survives; conviction does not emerge unscarred." },
  { id: "ceo-quits", title: "The Architect Leaves", kicker: "PERSONAL REASONS", description: "The mind behind the plan exits just before the critical test.", tone: "negative", targets: "one", effects: [{ trait: "managementQuality", traitDelta: -2, priceDelta: -0.21 }], narrative: "{company} enters the dreaded interim-identity era." },
  { id: "takeover-rumor", title: "Titan Circles", kicker: "SOURCES FAMILIAR", description: "A larger power is said to be watching. Nobody knows enough; everyone reacts anyway.", tone: "mixed", targets: "archetype", archetype: "future-takeover", effects: [{ trait: "marketHype", traitDelta: 2, priceDelta: 0.22 }], narrative: "Strategic characters levitate on rumor. Facts may arrive later." },
  { id: "permitting-delay", title: "The Map Refuses", kicker: "ANOTHER CONSULTATION", description: "The calendar discovers a new year between intention and permission.", tone: "negative", targets: "one", effects: [{ trait: "politicalRisk", traitDelta: 2, priceDelta: -0.14 }], narrative: "{company} learns that the territory gets a vote." },
  { id: "infra-breakthrough", title: "The Road Arrives", kicker: "THE MAP CHANGES", description: "A corridor opens and transforms what was possible yesterday.", tone: "positive", targets: "archetype", archetype: "infrastructure-winner", effects: [{ trait: "infrastructure", traitDelta: 2, priceDelta: 0.2 }], narrative: "Infrastructure stops being background and becomes destiny." },
  { id: "activist", title: "A Hard Question Appears", kicker: "A LETTER TO THE BOARD", description: "A powerful outsider demands discipline, focus, and fewer comforting stories.", tone: "mixed", targets: "one", effects: [{ trait: "managementQuality", traitDelta: 1, priceDelta: 0.08 }], narrative: "{company} gains pressure, scrutiny, and several extremely specific suggestions." },
  { id: "hype-wave", title: "Hype Bubble", kicker: "ATTENTION SURGE", description: "The room gets louder. Every story sounds inevitable for one dangerous turn.", tone: "mixed", targets: "all", effects: [{ trait: "marketHype", traitDelta: 1, priceDelta: 0.08 }], narrative: "The whole cast glows as attention outruns understanding." },
  { id: "dry-hole", title: "Empty Chamber", kicker: "NOT ECONOMIC", description: "The flagship mystery produces a technically fascinating quantity of disappointment.", tone: "negative", targets: "one", effects: [{ trait: "geologicalLuck", traitDelta: -2, priceDelta: -0.29 }], narrative: "{company} reminds everyone that reality cannot read promotional copy." },
  { id: "cost-shock", title: "Friction Tax", kicker: "EVERY INPUT COSTS MORE", description: "Labor, steel, diesel, and optimism all become more expensive at once.", tone: "negative", targets: "all", effects: [{ trait: "balanceSheet", traitDelta: -1, priceDelta: -0.07 }], narrative: "Friction rises across the world. Strong characters bend; weak ones make noises." },
];
