import type { GameEvent } from "../types";

export const events: GameEvent[] = [
  { id: "drill-surprise", title: "Drill Hole Surprise", kicker: "THE ROCK SPEAKS", description: "The assays are wider, richer, and considerably less imaginary than expected.", tone: "positive", targets: "one", effects: [{ trait: "geologicalLuck", traitDelta: 1, priceDelta: 0.24 }], narrative: "{company} rerates as the market discovers that geology sometimes reads the presentation deck." },
  { id: "commodity-boom", title: "Commodity Boom", kicker: "EVERYTHING HAS A BID", description: "Inventories tighten and generalists suddenly learn how commodity units work.", tone: "positive", targets: "commodity", commodity: "Copper", effects: [{ trait: "commodityExposure", traitDelta: 1, priceDelta: 0.16 }], narrative: "Copper names catch a broad cyclical bid. Exposure becomes genius—temporarily." },
  { id: "union-strike", title: "Union Strike", kicker: "THE GATES ARE CLOSED", description: "Operations stop while management rediscovers the stakeholder section of its annual report.", tone: "negative", targets: "one", effects: [{ trait: "executionSkill", traitDelta: -1, priceDelta: -0.17 }], narrative: "{company} loses production time and credibility as negotiations harden." },
  { id: "financing-closed", title: "Financing Closed", kicker: "DILUTION SHOCK", description: "The treasury is refilled at a painful discount. Survival improves while existing holders absorb the bill.", tone: "mixed", targets: "one", effects: [{ trait: "balanceSheet", traitDelta: 2, priceDelta: -0.06 }], narrative: "{company} buys runway with dilution. Optionality survives, ownership does not emerge unscarred." },
  { id: "ceo-quits", title: "CEO Quits", kicker: "PERSONAL REASONS", description: "The architect of the strategy leaves three weeks before the critical milestone.", tone: "negative", targets: "one", effects: [{ trait: "managementQuality", traitDelta: -2, priceDelta: -0.21 }], narrative: "{company} enters the dreaded interim-management era." },
  { id: "takeover-rumor", title: "Titan Takeover Rumor", kicker: "SOURCES FAMILIAR", description: "A mining major is said to be circling the asset. The source is anonymous and delighted.", tone: "mixed", targets: "archetype", archetype: "future-takeover", effects: [{ trait: "marketHype", traitDelta: 2, priceDelta: 0.22 }], narrative: "Strategic assets levitate on takeover chatter. Facts may arrive later." },
  { id: "permitting-delay", title: "Permitting Delay", kicker: "ANOTHER CONSULTATION", description: "The calendar discovers a new year between approval and construction.", tone: "negative", targets: "one", effects: [{ trait: "politicalRisk", traitDelta: 2, priceDelta: -0.14 }], narrative: "{company} adds twelve months to a timeline that was already doing creative writing." },
  { id: "infra-breakthrough", title: "Infrastructure Breakthrough", kicker: "THE ROAD ARRIVES", description: "A shared power and transport corridor changes project economics overnight.", tone: "positive", targets: "archetype", archetype: "infrastructure-winner", effects: [{ trait: "infrastructure", traitDelta: 2, priceDelta: 0.2 }], narrative: "Infrastructure stops being a footnote and becomes the whole valuation argument." },
  { id: "activist", title: "Activist Investor Appears", kicker: "A LETTER TO THE BOARD", description: "Someone with a meaningful stake and a very public PDF requests capital discipline.", tone: "mixed", targets: "one", effects: [{ trait: "managementQuality", traitDelta: 1, priceDelta: 0.08 }], narrative: "{company} gains a new shareholder and several extremely specific suggestions." },
  { id: "hype-wave", title: "Analyst Hype Wave", kicker: "TARGET PRICE: THE MOON", description: "Three initiations land in one morning. Every chart begins in the lower left.", tone: "mixed", targets: "all", effects: [{ trait: "marketHype", traitDelta: 1, priceDelta: 0.08 }], narrative: "The whole board glows green as attention outruns understanding." },
  { id: "dry-hole", title: "Dry Hole", kicker: "NOT ECONOMIC", description: "The flagship target produces a technically fascinating quantity of disappointment.", tone: "negative", targets: "one", effects: [{ trait: "geologicalLuck", traitDelta: -2, priceDelta: -0.29 }], narrative: "{company} reminds the market that rocks cannot read promotional copy." },
  { id: "cost-shock", title: "Cost Inflation Shock", kicker: "EVERY INPUT COSTS MORE", description: "Labor, steel, diesel, and optimism all become more expensive at once.", tone: "negative", targets: "all", effects: [{ trait: "balanceSheet", traitDelta: -1, priceDelta: -0.07 }], narrative: "Margins compress across the market. Strong balance sheets bend; weak ones make noises." },
];
