import type { InvestorCard } from "../types";

export const investorCards: InvestorCard[] = [
  { id: "builder-foundation", title: "The Builder", shortLore: "Sees a half-finished bridge and asks who can finish it.", passiveAbility: "+1 Wisdom when committing to high Builder DNA or Execution Skill.", drawback: "Hype-only characters feel less convincing.", synergies: ["Builder DNA", "Execution Skill", "Patience"], rarity: "Common", icon: "△", effect: "builder" },
  { id: "contrarian-lantern", title: "The Contrarian", shortLore: "Carries a lantern into rooms everyone has left.", passiveAbility: "+1 Wisdom when pledging to low-hype resilient characters.", drawback: "Momentum waves are easier to underplay.", synergies: ["Low Hype", "Balance Sheet", "Investigate"], rarity: "Common", icon: "◇", effect: "contrarian" },
  { id: "empire-map", title: "The Empire Builder", shortLore: "Thinks in corridors, systems, and second-order effects.", passiveAbility: "+1 Legacy when holding 3+ commitments.", drawback: "Concentrated conviction grows slower.", synergies: ["Infrastructure", "Credibility", "Diversification"], rarity: "Common", icon: "▦", effect: "empire" },
  { id: "compounder-engine", title: "The Compounder", shortLore: "Prefers the quiet machine that keeps turning.", passiveAbility: "Cash Cow and Hidden Royalty commitments suffer slightly less downside.", drawback: "Explosive upside is modestly dampened.", synergies: ["Balance Sheet", "Patience", "Cash Cow"], rarity: "Common", icon: "▤", effect: "compounder" },
  { id: "risk-ledger", title: "The Risk Manager", shortLore: "Knows survival is a strategy, not a mood.", passiveAbility: "First severe downside each world reaction is softened.", drawback: "Optionality bets add less Wisdom.", synergies: ["Trim", "Patience", "Balance Sheet"], rarity: "Common", icon: "▣", effect: "risk" },
  { id: "story-spark", title: "The Story Teller", shortLore: "Understands that belief can move before proof.", passiveAbility: "+1 Wisdom when a high-hype commitment survives a reaction.", drawback: "Fragile stories punish Wisdom harder.", synergies: ["Market Hype", "Momentum", "Future Takeover"], rarity: "Common", icon: "✦", effect: "story" },
  { id: "allocator-scale", title: "The Capital Allocator", shortLore: "Every pledge must beat the next best use.", passiveAbility: "Trims add +1 Wisdom when not panic selling.", drawback: "Idle capital costs 1 Legacy on quiet turns.", synergies: ["Trim", "Rebalance", "Optionality"], rarity: "Common", icon: "⚖", effect: "allocator" },
  { id: "macro-tide", title: "The Macro Surfer", shortLore: "Reads the wave before choosing the board.", passiveAbility: "+1 Wisdom when backing high Commodity Exposure.", drawback: "Company-specific execution matters slightly less to you.", synergies: ["Commodity Exposure", "Sleeping Giant", "Infrastructure"], rarity: "Common", icon: "≈", effect: "macro" },
  { id: "optionality-key", title: "The Optionality Collector", shortLore: "Collects keys before knowing which door matters.", passiveAbility: "Optionality actions cost 1 less after the first draft.", drawback: "Downside from asymmetric bets can cut deeper.", synergies: ["Optionality", "Lottery Ticket", "Discovery"], rarity: "Common", icon: "✧", effect: "optionality" },
  { id: "discovery-lens", title: "The Discovery Hunter", shortLore: "Believes the unknown is an asset if studied first.", passiveAbility: "First Investigation each run grants +1 extra Wisdom.", drawback: "Uninvestigated commitments feel riskier.", synergies: ["Attention", "Geological Luck", "Hidden Traits"], rarity: "Common", icon: "◎", effect: "discovery" },

  { id: "builder-scar-tissue", title: "Scar Tissue Builder", shortLore: "Trusts teams that have already paid tuition.", passiveAbility: "Builder commitments gain more from Hold Conviction.", drawback: "Weak Execution Skill costs extra Wisdom.", synergies: ["Builder", "Hold", "Execution Skill"], rarity: "Rare", icon: "▲", effect: "builder" },
  { id: "contrarian-empty-room", title: "Empty Room Thesis", shortLore: "Looks for the chair nobody wants to sit in.", passiveAbility: "Low-hype commitments gain +2 Wisdom after positive reactions.", drawback: "Popular characters add less Legacy.", synergies: ["Contrarian", "Low Hype", "Balance Sheet"], rarity: "Rare", icon: "◈", effect: "contrarian" },
  { id: "empire-supply-line", title: "Supply Line Doctrine", shortLore: "No empire survives without roads.", passiveAbility: "Infrastructure Winner commitments add +1 Legacy each reflect.", drawback: "Lottery Tickets receive less benefit from patience.", synergies: ["Infrastructure", "Empire Builder", "Credibility"], rarity: "Rare", icon: "⌘", effect: "empire" },
  { id: "compounder-flywheel", title: "The Flywheel", shortLore: "Small advantages repeat until they become gravity.", passiveAbility: "Holding through uncertainty grants +1 extra Wisdom with resilient characters.", drawback: "Fast trims add less Wisdom.", synergies: ["Compounder", "Hold", "Cash Cow"], rarity: "Rare", icon: "◴", effect: "compounder" },
  { id: "risk-kill-switch", title: "Kill Switch", shortLore: "The best loss is the one that stops early.", passiveAbility: "Panic selling penalty is reduced once.", drawback: "Momentum Trader score grows slower.", synergies: ["Risk Manager", "Trim", "Capital Preservation"], rarity: "Rare", icon: "■", effect: "risk" },
  { id: "momentum-tape-reader", title: "The Momentum Trader", shortLore: "Hears the crowd speed up before the chart admits it.", passiveAbility: "High-hype winners receive extra upside during positive reactions.", drawback: "Reversals punish late belief.", synergies: ["Hype", "Trim", "Story Teller"], rarity: "Rare", icon: "↗", effect: "momentum" },
  { id: "allocator-opportunity-cost", title: "Opportunity Cost", shortLore: "Every yes hides a no.", passiveAbility: "Keeping 200+ unused capital adds +1 Wisdom at reflect.", drawback: "Overconcentration loses 1 Legacy.", synergies: ["Capital Allocator", "Optionality", "Risk"], rarity: "Rare", icon: "□", effect: "allocator" },
  { id: "macro-cycle-clock", title: "Cycle Clock", shortLore: "The calendar is a character too.", passiveAbility: "Commodity-linked positive events add +2 Wisdom.", drawback: "Company misses hurt more if you ignored traits.", synergies: ["Macro", "Commodity Exposure", "Patience"], rarity: "Rare", icon: "◷", effect: "macro" },
  { id: "optionality-long-tail", title: "Long Tail Map", shortLore: "The huge outcome hides in the weird corner.", passiveAbility: "Asymmetric Bet upside is amplified slightly more.", drawback: "Asymmetric downside is also amplified.", synergies: ["Optionality", "Lottery Ticket", "Future Takeover"], rarity: "Rare", icon: "⟡", effect: "optionality" },
  { id: "discovery-core-sample", title: "Core Sample Mind", shortLore: "Cuts into the story and studies the layers.", passiveAbility: "Investigations cost 1 less Attention once per turn.", drawback: "Holding without investigation grants less Wisdom.", synergies: ["Discovery", "Attention", "Geological Luck"], rarity: "Rare", icon: "◉", effect: "discovery" },

  { id: "builder-cathedral", title: "Cathedral Builder", shortLore: "Plays for projects that outlive the run.", passiveAbility: "High Builder DNA + Infrastructure commitments gain +3 Legacy on positive reactions.", drawback: "Permitting-style setbacks hurt patience.", synergies: ["Builder", "Infrastructure", "Empire"], rarity: "Epic", icon: "⛏", effect: "builder" },
  { id: "contrarian-iceberg", title: "Iceberg Thesis", shortLore: "Most of the value is below the waterline.", passiveAbility: "Hidden-trait reveals on low-hype characters grant +3 Wisdom.", drawback: "High-hype commitments start with -1 Wisdom.", synergies: ["Contrarian", "Discovery", "Hidden Royalty"], rarity: "Epic", icon: "◆", effect: "contrarian" },
  { id: "empire-network-effects", title: "Network Effects", shortLore: "Each good node makes the next one stronger.", passiveAbility: "Each distinct archetype committed adds +1 Legacy at reflect.", drawback: "Single-character runs lose Wisdom faster.", synergies: ["Empire", "Diversification", "Capital Allocator"], rarity: "Epic", icon: "✣", effect: "empire" },
  { id: "compounder-sleep-well", title: "Sleep-Well Machine", shortLore: "Boring is a superpower when the world panics.", passiveAbility: "Reflect grants +2 Wisdom if no commitment fell badly.", drawback: "Optionality Hunter score grows slower.", synergies: ["Compounder", "Risk Manager", "Cash Cow"], rarity: "Epic", icon: "◼", effect: "compounder" },
  { id: "risk-margin-safety", title: "Margin of Safety", shortLore: "Leaves room for being wrong, which is often.", passiveAbility: "Low-hype, strong-balance commitments get downside protection.", drawback: "Hype Wave upside is dampened.", synergies: ["Risk", "Contrarian", "Balance Sheet"], rarity: "Epic", icon: "▰", effect: "risk" },
  { id: "story-reflexivity", title: "Reflexivity Engine", shortLore: "The story changes the outcome it describes.", passiveAbility: "Positive reactions to high-hype characters can add +2 Wisdom and +2 Legacy.", drawback: "Negative reactions to fragile stories cost extra Wisdom.", synergies: ["Story Teller", "Momentum", "Hype"], rarity: "Epic", icon: "✹", effect: "story" },
  { id: "allocator-sunken-cost", title: "No Sunk Cost", shortLore: "Cuts the rope without arguing with the past.", passiveAbility: "Abandoning a weak thesis after new evidence grants +3 Wisdom.", drawback: "Holding losers for conviction grants less Legacy.", synergies: ["Allocator", "Risk", "Trim"], rarity: "Epic", icon: "✂", effect: "allocator" },
  { id: "macro-regime-shift", title: "Regime Shift", shortLore: "Knows when the board itself has changed.", passiveAbility: "All-cycle events grant extra Wisdom if you hold Macro exposure.", drawback: "Idiosyncratic discoveries grant less Legacy.", synergies: ["Macro", "Commodity", "Sleeping Giant"], rarity: "Epic", icon: "☍", effect: "macro" },
  { id: "optionality-convexity", title: "Convexity", shortLore: "Wants small losses and weirdly large wins.", passiveAbility: "First positive asymmetric event grants +4 Wisdom.", drawback: "First negative asymmetric event costs +2 extra Wisdom.", synergies: ["Optionality", "Asymmetric Bet", "Discovery"], rarity: "Epic", icon: "⌁", effect: "optionality" },
  { id: "discovery-first-principles", title: "First Principles Prospector", shortLore: "Breaks the thesis down until only rock remains.", passiveAbility: "Revealing Geological Luck or Execution Skill grants +3 Wisdom.", drawback: "Credibility plays cost 1 extra resource.", synergies: ["Discovery", "Geology", "Execution"], rarity: "Epic", icon: "⊙", effect: "discovery" },

  { id: "legend-builder-master-plan", title: "Master Plan Builder", shortLore: "Can see the finished city from the first road.", passiveAbility: "Builder + Infrastructure commitments compound Legacy every reflect.", drawback: "If execution breaks, Wisdom loss is severe.", synergies: ["Builder", "Empire Builder", "Infrastructure"], rarity: "Legendary", icon: "🏛", effect: "builder" },
  { id: "legend-contrarian-black-snow", title: "Black Snow Contrarian", shortLore: "Finds warmth in the trade everyone calls frozen.", passiveAbility: "A neglected winner can double its Wisdom reward.", drawback: "Popular winners barely move your philosophy.", synergies: ["Contrarian", "Low Hype", "Hidden Royalty"], rarity: "Legendary", icon: "❖", effect: "contrarian" },
  { id: "legend-empire-capital-city", title: "Capital City", shortLore: "Turns separate theses into a civilization.", passiveAbility: "Four or more commitments create an Empire bonus each turn.", drawback: "One catastrophic weak link costs extra Legacy.", synergies: ["Empire", "Allocator", "Macro"], rarity: "Legendary", icon: "♜", effect: "empire" },
  { id: "legend-compounder-perpetual", title: "Perpetual Engine", shortLore: "A machine that teaches the player to wait.", passiveAbility: "Every second Hold through uncertainty grants +4 Wisdom.", drawback: "Momentum gains are heavily dampened.", synergies: ["Compounder", "Patience", "Risk Manager"], rarity: "Legendary", icon: "∞", effect: "compounder" },
  { id: "legend-risk-fortress", title: "Fortress Mind", shortLore: "The storm can rage; the gates were built for this.", passiveAbility: "Once per run, prevents a major Wisdom loss.", drawback: "Legendary upside bonuses are smaller.", synergies: ["Risk", "Balance Sheet", "Patience"], rarity: "Legendary", icon: "▛", effect: "risk" },
  { id: "legend-story-market-dream", title: "Market Dream Weaver", shortLore: "Knows belief is a resource with its own supply curve.", passiveAbility: "High-hype positive streaks add large Legacy.", drawback: "Reversals become emotionally expensive.", synergies: ["Story", "Momentum", "Optionality"], rarity: "Legendary", icon: "☄", effect: "story" },
  { id: "legend-allocator-grandmaster", title: "Grandmaster Allocator", shortLore: "Moves capital like pieces on a living board.", passiveAbility: "Each disciplined trim or redeploy grants +3 Wisdom.", drawback: "Doing nothing with idle capital costs Legacy.", synergies: ["Allocator", "Risk", "Contrarian"], rarity: "Legendary", icon: "♛", effect: "allocator" },
  { id: "legend-macro-great-wave", title: "The Great Wave", shortLore: "Does not predict the ocean; learns to ride it.", passiveAbility: "Macro-aligned world responses strongly boost Wisdom.", drawback: "Single-company conviction bonuses weaken.", synergies: ["Macro", "Commodity Exposure", "Cycle"], rarity: "Legendary", icon: "🌊", effect: "macro" },
  { id: "legend-optionality-moonshot", title: "Moonshot Collector", shortLore: "Owns doors that should not exist yet.", passiveAbility: "First major optionality win grants massive Legacy.", drawback: "Misses cost patience and Wisdom.", synergies: ["Optionality", "Discovery", "Lottery Ticket"], rarity: "Legendary", icon: "☾", effect: "optionality" },
  { id: "legend-discovery-oracle", title: "Discovery Oracle", shortLore: "Does not guess; listens until the hidden thing answers.", passiveAbility: "Every third reveal grants a large Wisdom burst.", drawback: "Committing blind costs extra Wisdom.", synergies: ["Discovery", "Attention", "Hidden Traits"], rarity: "Legendary", icon: "☼", effect: "discovery" },
];

export const investorCardMap = Object.fromEntries(
  investorCards.map((card) => [card.id, card]),
) as Record<string, InvestorCard>;
