import type { RouteScenario } from "../types";

export const routeScenarios: RouteScenario[] = [
  { id: "quiet-market", title: "The Quiet Market", subtitle: "Lower noise, fewer miracles", lore: "The room empties. Serious characters become easier to hear.", tradeoff: "Gain Patience, but the next event avoids extreme upside.", kind: "safe", icon: "◌", eventTone: "mixed", resourceDelta: { patience: 1 }, wisdomDelta: 1, legacyDelta: 0 },
  { id: "research-window", title: "Research Window", subtitle: "Truth before timing", lore: "A narrow window opens to inspect what everyone else is rushing past.", tradeoff: "Gain Attention, but surrender a little Capital to the work.", kind: "research", icon: "◎", eventTarget: "one", resourceDelta: { attention: 2, capital: -35 }, wisdomDelta: 1, legacyDelta: 0 },
  { id: "political-storm", title: "Political Storm", subtitle: "Conviction enters public weather", lore: "Rules, coalitions, and old promises begin moving at once.", tradeoff: "Gain Credibility for entering the room; negative regional events become more likely.", kind: "crisis", icon: "⚑", eventTone: "negative", eventTarget: "region", resourceDelta: { credibility: 1 }, wisdomDelta: 2, legacyDelta: 1 },
  { id: "rare-auction", title: "The Closed Auction", subtitle: "Scarcity recognizes preparation", lore: "Only a few allocators are invited. Nobody explains why.", tradeoff: "Spend Credibility for a better chance at rare, focused events.", kind: "rare", icon: "✦", eventTarget: "archetype", resourceDelta: { credibility: -1, optionality: 1 }, wisdomDelta: 2, legacyDelta: 1 },
  { id: "frontier-road", title: "Frontier Road", subtitle: "Optionality with teeth", lore: "The map offers speed, scale, and several ways to be wrong.", tradeoff: "Gain Optionality; accept stronger event volatility.", kind: "unknown", icon: "◇", resourceDelta: { optionality: 2, patience: -1 }, wisdomDelta: 1, legacyDelta: 0 },
  { id: "council-chamber", title: "Council Chamber", subtitle: "Influence before ownership", lore: "The next advantage may come from shaping the table, not buying a seat.", tradeoff: "Trade Capital for Credibility and Legacy.", kind: "influence", icon: "♜", resourceDelta: { capital: -50, credibility: 2 }, wisdomDelta: 1, legacyDelta: 2 },
  { id: "distressed-bazaar", title: "Distressed Bazaar", subtitle: "Everything is cheap for a reason", lore: "Broken stories gather where confident money refuses to look.", tradeoff: "Neglected companies appear; negative events are more likely.", kind: "crisis", icon: "↘", eventTone: "negative", resourceDelta: { capital: 40, patience: -1 }, wisdomDelta: 1, legacyDelta: 0 },
  { id: "builder-summit", title: "Builder Summit", subtitle: "Operators compare scars", lore: "People who finish difficult things quietly exchange what they know.", tradeoff: "Spend Attention to gain Patience and execution-biased encounters.", kind: "influence", icon: "▣", eventTarget: "industry", resourceDelta: { attention: -1, patience: 2 }, wisdomDelta: 2, legacyDelta: 1 },
  { id: "signal-festival", title: "Signal Festival", subtitle: "Narrative becomes weather", lore: "Stories move faster than facts and everyone can feel the acceleration.", tradeoff: "Gain Capital momentum; mixed and positive events become more likely.", kind: "rare", icon: "↗", eventTone: "positive", resourceDelta: { capital: 30, optionality: 1 }, wisdomDelta: 0, legacyDelta: 0 },
  { id: "long-winter", title: "The Long Winter", subtitle: "Only durability compounds", lore: "Catalysts disappear. Balance sheets and temperament inherit the turn.", tradeoff: "Gain Patience and Wisdom; lose immediate Optionality.", kind: "safe", icon: "❄", eventTone: "mixed", resourceDelta: { patience: 2, optionality: -1 }, wisdomDelta: 2, legacyDelta: 0 },
  { id: "black-box", title: "The Black Box", subtitle: "Choose before knowing", lore: "The route is deliberately obscured. Curiosity and recklessness look identical from outside.", tradeoff: "Unknown event bias. Gain Optionality and risk a resource shock.", kind: "unknown", icon: "?", resourceDelta: { optionality: 1, attention: -1 }, wisdomDelta: 2, legacyDelta: 0 },
  { id: "public-mandate", title: "Public Mandate", subtitle: "Scale meets responsibility", lore: "The world offers permission, then watches what you do with it.", tradeoff: "Gain Capital and Legacy; political events become more likely.", kind: "influence", icon: "◆", eventTarget: "region", resourceDelta: { capital: 55, credibility: -1 }, wisdomDelta: 1, legacyDelta: 2 },
  { id: "discovery-ridge", title: "Discovery Ridge", subtitle: "The hidden layer is close", lore: "Evidence is incomplete, but several unrelated signals begin pointing uphill.", tradeoff: "Gain Attention and Optionality; single-company shocks become more likely.", kind: "research", icon: "△", eventTarget: "one", resourceDelta: { attention: 1, optionality: 1 }, wisdomDelta: 1, legacyDelta: 0 },
  { id: "capital-strike", title: "Capital Strike", subtitle: "Nobody wants to fund the future", lore: "The market stops rewarding ambition and begins auditing survival.", tradeoff: "Preserve Credibility; broad negative events become more likely.", kind: "crisis", icon: "⊘", eventTone: "negative", eventTarget: "all", resourceDelta: { credibility: 1, capital: -25 }, wisdomDelta: 2, legacyDelta: 0 },
  { id: "patient-harbor", title: "Patient Harbor", subtitle: "Time becomes an asset", lore: "A protected interval lets durable systems work without applause.", tradeoff: "Gain Patience; sacrifice Attention and immediate discovery.", kind: "safe", icon: "⌛", eventTone: "mixed", resourceDelta: { patience: 2, attention: -1 }, wisdomDelta: 1, legacyDelta: 1 },
  { id: "rumor-exchange", title: "Rumor Exchange", subtitle: "Information without provenance", lore: "Every whisper is useful to someone, especially the person selling it.", tradeoff: "Gain Optionality; hype-driven events become more likely.", kind: "unknown", icon: "≈", eventTone: "mixed", resourceDelta: { optionality: 2, credibility: -1 }, wisdomDelta: 0, legacyDelta: 0 },
  { id: "operator-rescue", title: "Operator Rescue", subtitle: "Save the machine or save yourself", lore: "A capable team asks for time before the market closes the door.", tradeoff: "Spend Capital and Patience for Wisdom and Legacy.", kind: "rare", icon: "✚", eventTarget: "one", resourceDelta: { capital: -70, patience: -1 }, wisdomDelta: 3, legacyDelta: 2 },
  { id: "macro-crossroads", title: "Macro Crossroads", subtitle: "The cycle chooses a direction", lore: "Supply, policy, and capacity stop cancelling each other out.", tradeoff: "Industry-wide events become more likely; gain Attention.", kind: "research", icon: "⌁", eventTarget: "industry", resourceDelta: { attention: 1 }, wisdomDelta: 2, legacyDelta: 0 },
];

export const routeMap = Object.fromEntries(routeScenarios.map((route) => [route.id, route])) as Record<string, RouteScenario>;
